# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python

name: DEV - S3 Deploy

env:
  APP_NAME: my-awesome-react-app
  APP_ENV: dev
  AWS_REGION: us-east-1

on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [ master ]

jobs:
  build_node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: |
          echo "Downloading dependencies"
          yarn

          echo "Building React app"
          yarn build:${{env.APP_ENV}}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            build

  s3_upload:
    needs: [build_node]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download all previous job artifacts
        uses: actions/download-artifact@v2
        with:
          path: downloaded
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.AWS_REGION}}
      - run: |
          echo "Going to downloaded artifacts directory"
          cd ./downloaded/artifacts

          echo "Uploading to S3 bucket"
          aws s3 sync . s3://${{secrets.S3_BUCKET}}
